### PR TITLE
Update Path,Types and interfaces of led

### PR DESCRIPTION
**Pull request by xiaoyu3x**
…light

### CODE REVIEW

**Comment by xiaoyu3x** [comment]
hello, @gvancuts

Please help me  merge this PR if you think this PR is OK

**Comment by ttzeng** [comment]
@xiaoyu3x thanks for correcting this bug, no wonder Theresa's web portal doesn't present this resource with a LED card.

**Comment by gvancuts** [comment]
It sounds like @ttzeng agrees to the merging :-) ... merging it now.

**Comment by gvancuts** [comment]
Actually, I'll revert this merge and would like to ask you @xiaoyu3x to re-submit the same PR but with a sign-off-by in the commit message. Can you do that?

**Pull request merged**
