### PR TITLE
gateway/README.md: fix instructions for native installation

### LINKED ISSUE #188: Misuse "sudo" leads to happen error during running gateway-server.js
## Description:

Due to misuse "sudo" command in the [README.md](https://github.com/01org/SmartHome-Demo/tree/master/gateway#native-installation) to install lib package(iot-rest-api-server), error happens when running gateway-server.js.

## Steps:
1. Clone smartHome-demo
```
$ cd /opt
$ sudo git clone https://github.com/01org/SmartHome-Demo
$ cd SmartHome-Demo
```
2. Install node.js dependencies
```
$ cd /opt/SmartHome-Demo
$ sudo npm install iot-rest-api-server express websocket
$ sudo npm install mraa #optional
```
3.Start the Home GW services
```
$ cd /opt/SmartHome-Demo
$ /usr/bin/node gateway/gateway-server.js & # Start server with 3D UI and rules engine.
```

## Actual Result:
selection_001

## Expect Result:
Home GW service starts successfully and no error popups

## Comment
This issue hasn't relative with node version and current node version is 6.11.0. 
It will popups error when node version is 7.*.* , 8.*.* or 9.*.*
capture

## Proposal:

Remove 'sudo' and these commands are used under the ordinary user.
e.g.
```
$ sudo git clone https://github.com/01org/SmartHome-Demo
$ sudo npm install iot-rest-api-server express websocket
$ sudo npm install mraa #optional
```

modify to 
```
$ git clone https://github.com/01org/SmartHome-Demo
$ npm install iot-rest-api-server express websocket
$ npm install mraa #optional
```

### PR DESCRIPTION
**Pull request by gvancuts**
The instructions to install and run the gateway functions natively
are incorrect. This patch fixes the instructions and also adjusts
the sample systemd files provided accordingly.

Fix #188 

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by xiaoyu3x** [comment]
hi, @gvancuts 
Glad to see your PR and it is valid except a small issue.
'npm install' will fail due to permission  issue if [SmartHome-Demo](https://github.com/01org/SmartHome-Demo) is cloned under 'root' user. 
capture3
So I think command 
`sudo git clone https://github.com/01org/SmartHome-Demo`
modify to 
`git clone https://github.com/01org/SmartHome-Demo`

**Comment by gvancuts** [comment]
Thanks for your testing @xiaoyu3x and sorry for the long silence on this, I only got back to it tonight.

It's not possible to clone a repo under `/opt` if you're not `root` so I ended up using a slightly different approach by making the user clone the repo in his home (`$HOME`) directory. I automatically adjust the `systemd` service files as well just before copying them by using `sed`.

I have not tested these new instructions so I would appreciate if you could and provide me with your feedback. Thanks!

**Comment by xiaoyu3x** [comment]
Sorry, @gvancuts 
I just see your comment, I will verified this PR according to your comment.
I will update comment until test over.

**Comment by xiaoyu3x** [comment]
hi, @gvancuts 
This PR is prefect and it can realize test task.

**Comment by gvancuts** [comment]
Thanks @xiaoyu3x ! I will merge this

**Pull request merged**
